---
- name: Automember default group not set
  hosts: ipaserver
  become: true
  tasks:
  - name: Ensure automember default group is not set
    ipaautomember:
      ipaadmin_password: SomeADMINpassword
      automember_type: group
      default_group: ""
