---
- name: Server no location example
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure server "ipareplica1.example.com" with no location
    ipaserver:
      ipaadmin_password: SomeADMINpassword
      name: ipareplica1.example.com
      location: ""
