---
- name: Permission absent example
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure permission is absent
    ipapermission:
      ipaadmin_password: SomeADMINpassword
      name: TestPerm1
      state: absent
