---
- name: Playbook to manage IPA role.
  hosts: ipaserver
  become: yes
  gather_facts: no

  tasks:
  - name: Ensure role is present.
    iparole:
      ipaadmin_password: SomeADMINpassword
      name: somerole
      description: A role in IPA.
