---
- name: Servicedelegationtarget present example
  hosts: ipaserver
  become: no

  tasks:
  - name: Ensure servicedelegationtarget test-delegation-target is present
    ipaservicedelegationtarget:
      ipaadmin_password: SomeADMINpassword
      name: test-delegation-target
