---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Ensure vault is absent.
    ipavault:
      ipaadmin_password: SomeADMINpassword
      name: stdvault
      username: admin
      state: absent
