---
- name: Playbook to handle users
  hosts: ipaserver
  become: true

  tasks:
  - name: Disable user pinky
    ipauser:
      ipaadmin_password: SomeADMINpassword
      name: pinky
      state: disabled
