---
- name: Playbook to handle users
  hosts: ipaserver
  become: true

  tasks:
  - name: Unlock users pinky and brain
    ipauser:
      ipaadmin_password: SomeADMINpassword
      name: pinky,brain
      state: unlocked
