---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Ensure sudooption '!root' is absent in sudorule
    ipasudorule:
      ipaadmin_password: SomeADMINpassword
      name: testrule1
      sudooption: "!root"
      action: member
      state: absent
