---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Ensure host server is absent in HBAC Rule allhosts
    ipahbacrule:
      ipaadmin_password: SomeADMINpassword
      name: allhosts
      host: server
      action: member
      state: absent
